terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

resource "aws_launch_template" "app" {
  name_prefix = var.name

  # Generated by packer - see more at /amis
  # packer build application.pkr.hcl
  image_id      = var.image_id
  instance_type = var.instance_type
}

resource "aws_autoscaling_group" "app" {
  availability_zones = var.availability_zones
  desired_capacity   = var.capacity.desired
  max_size           = var.capacity.max
  min_size           = var.capacity.min

  launch_template {
    id      = aws_launch_template.app.id
    version = "$Latest"
  }
}
