terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

resource "aws_launch_template" "app" {
  name_prefix = var.name

  # Generated by packer - see more at /amis
  # packer build application.pkr.hcl
  image_id        = var.image_id
  instance_type   = var.instance_type
  security_groups = data.aws_security_groups.app.ids
}

resource "aws_autoscaling_group" "app" {
  desired_capacity    = var.capacity.desired
  max_size            = var.capacity.max
  min_size            = var.capacity.min
  vpc_zone_identifier = var.subnet_app_ids

  launch_template {
    id      = aws_launch_template.app.id
    version = "$Latest"
  }
}


resource "aws_lb" "default" {
  name               = var.name
  internal           = false
  load_balancer_type = "application"
  security_groups    = data.aws_security_groups.lb.ids
  subnets            = var.subnet_public_ids
}

resource "aws_lb_target_group" "app" {
  name     = var.name
  port     = 80
  protocol = "HTTP"
  vpc_id   = var.vpc_id
}

resource "aws_autoscaling_attachment" "asg_attachment" {
  autoscaling_group_name = aws_autoscaling_group.app.id
  alb_target_group_arn   = aws_lb_target_group.app.arn
}
